(function (app) {
  function renderGuideView() {
    const header = app.viewUtils.pageHeader;
    const chapters = [
      ["01", "guide-recettes", "Trouver une recette", `<p>La recherche porte sur le nom, la description, la catégorie et le type de cuisine. Les filtres servent à réduire les résultats par catégorie, préférences alimentaires, durée totale ou préparation active. Vous pouvez aussi afficher vos favoris.</p><p>Le score compare les noms d’ingrédients au garde-manger et ne tient pas compte des quantités. Sans ingrédient enregistré, aucun score n’est affiché. Le panneau de gauche se replie avec sa flèche pour élargir la grille.</p><button class="action-guide" type="button" data-view="recettes">Parcourir les recettes <span aria-hidden="true">→</span></button>`],
      ["02", "guide-preparation", "Préparer plusieurs recettes", `<ol class="etapes-guide"><li><strong>Choisir.</strong> Utilisez « Préparer + » sur les cartes qui vous intéressent.</li><li><strong>Regrouper.</strong> Ouvrez « Préparer » dans la navigation pour voir le plan et les ingrédients communs.</li><li><strong>Vérifier.</strong> Cochez « Prêt » au fur et à mesure; la progression se met à jour. Développez un ingrédient pour voir ses quantités par recette.</li><li><strong>Organiser.</strong> Créez des groupes, puis glissez-y les ingrédients; le menu « Groupe » offre la même action sans glisser.</li><li><strong>Ranger.</strong> Pour chaque manque, cochez « Ajouter au garde-manger » ou « Ajouter à l’épicerie ». Un ingrédient déjà au garde-manger peut en être retiré depuis son plan.</li></ol><p>Les quantités restent séparées par recette afin de ne pas additionner des unités différentes. Le plan et sa progression restent mémorisés dans ce navigateur.</p><button class="action-guide" type="button" data-view="preparation">Ouvrir le plan de préparation <span aria-hidden="true">→</span></button>`],
      ["03", "guide-ingredients", "Garde-manger et épicerie", `<p>Dans « Explorer les ingrédients », une tuile verte est déjà au garde-manger. Cliquez pour ajouter ou retirer un ingrédient; « Tout ajouter au garde-manger » ajoute le catalogue complet.</p><p>L’inventaire et la liste d’épicerie sont distincts. Depuis une recette, « Épicerie + » ajoute les noms d’ingrédients manquants, sans leurs quantités. Cocher un article de la liste le transfère au garde-manger. La liste peut être exportée en CSV.</p>`],
      ["04", "guide-fiche", "Lire une fiche recette", `<p>La fiche présente les ingrédients, portions, étapes et source lorsqu’elle est fournie. Les cases près des ingrédients servent de pense-bête et restent cochées quand vous rouvrez la fiche.</p><p>Changer le nombre de portions recalcule les quantités numériques, mais pas les étapes ni les durées. Le volume, l’épaisseur et le récipient peuvent nécessiter une adaptation ou plusieurs fournées. Pour les viandes, volailles et poissons, contrôlez la température à cœur avec un thermomètre.</p><a class="lien-guide" href="https://www.canada.ca/fr/sante-canada/services/conseils-generaux-salubrite/temperatures-securitaires-cuisson-interne.html" target="_blank" rel="noopener noreferrer">Températures sécuritaires de Santé Canada <span aria-hidden="true">↗</span></a>`],
      ["05", "guide-limites", "Données et limites", `<p>Le carnet fonctionne localement et ne demande ni compte ni installation. Les préférences, le plan, le garde-manger et la liste sont conservés par le navigateur; ils ne sont pas synchronisés entre appareils.</p><p>Les étiquettes de préférences et le score sont des repères, pas des garanties médicales. Vérifiez les ingrédients et les allergènes sur les emballages. Les champs facultatifs des recettes, comme les calories et les valeurs nutritives détaillées, ne sont pas affichés dans les fiches.</p>`]
    ].map(([number, id, title, content]) => `<section class="chapitre-guide" id="${id}" aria-labelledby="${id}-titre"><span class="numero-chapitre-guide" aria-hidden="true">${number}</span><div class="contenu-chapitre-guide"><h2 id="${id}-titre">${title}</h2>${content}</div></section>`).join("");
    const contents = [
      ["01", "guide-recettes", "Trouver une recette"],
      ["02", "guide-preparation", "Préparer plusieurs recettes"],
      ["03", "guide-ingredients", "Ingrédients et épicerie"],
      ["04", "guide-fiche", "Fiche recette"],
      ["05", "guide-limites", "Données et limites"]
    ].map(([number, id, label]) => `<a href="#${id}"><span>${number}</span>${label}</a>`).join("");

    return `<section class="vue-guide contenu-vue">${header("Repères", "Guide", "Des réponses courtes pour passer de l’idée au repas.")}<div class="guide-introduction"><span class="guide-marqueur" aria-hidden="true">À</span><p>Un parcours simple : trouvez vos idées, choisissez quoi cuisiner, puis vérifiez ce qu’il vous manque.</p></div><div class="disposition-guide"><nav class="sommaire-guide" aria-label="Sommaire du guide"><p>Dans ce guide</p>${contents}</nav><div class="chapitres-guide">${chapters}</div></div></section>`;
  }

  app.renderGuideView = renderGuideView;
})(window.AtTable = window.AtTable || {});
